dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install libunwind8

install:
  - sudo $TRAVIS_BUILD_DIR/build.sh /usr/local/bin --yes-all

before_script:
  - netpkg-tool --help
  - sudo netpkg-tool --install-sdk --yes-all
  - source ~/.bashrc
  - netpkg-tool --help
  - dotnet new sln

script:
  - git clone https://github.com/phil-harmoniq/ArgTest $TRAVIS_BUILD_DIR/ArgTest
  - netpkg-tool $TRAVIS_BUILD_DIR/ArgTest $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/ArgTest.npk one two thr33 --npk-v four
  - netpkg-tool $TRAVIS_BUILD_DIR/ArgTest $TRAVIS_BUILD_DIR --scd
  - $TRAVIS_BUILD_DIR/ArgTest.AppImage one two thr33 --npk-v four
  - netpkg-tool $TRAVIS_BUILD_DIR/ArgTest $TRAVIS_BUILD_DIR -v -n Arrrg --keep
  - $TRAVIS_BUILD_DIR/ArgTest.npk one two thr33 --npk-v four
